kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: images
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
