apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../global/cluster-certificates
- credentialrequest-azure.yaml

patches:
- patch: |-
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: letsencrypt-ingress
      namespace: openshift-ingress
    spec:
      commonName: "*.apps.groundbreaker-azure.4xvtd.azure.redhatworkshops.io"
      dnsNames:
      - "*.apps.groundbreaker-azure.4xvtd.azure.redhatworkshops.io"
- patch: |-
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: letsencrypt-api
      namespace: openshift-config
    spec:
      commonName: "api.groundbreaker-azure.4xvtd.azure.redhatworkshops.io"
      dnsNames:
      - "api.groundbreaker-azure.4xvtd.azure.redhatworkshops.io"
- patch: |-
    apiVersion: config.openshift.io/v1
    kind: APIServer
    metadata:
      name: cluster
    spec:
      servingCerts:
        namedCertificates:
        - names:
          - "api.groundbreaker-azure.4xvtd.azure.redhatworkshops.io"
          servingCertificate:
            name: letsencrypt-api
- patch: |-
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: letsencrypt
    spec:
      acme:
        solvers:
        - dns01:
            azureDNS:
              clientID: d332b402-7cc3-4544-9520-e82290396434
              clientSecretSecretRef:
                name: cloud-credentials
                key: azure_client_secret
              subscriptionID: 5356b74b-bc41-46e6-bd14-9f496b0a9977
              tenantID: 64dc69e4-d083-49fc-9569-ebece1dd1408
              resourceGroupName: openenv-4xvtd
              hostedZoneName: 4xvtd.azure.redhatworkshops.io
