apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - google:
      clientID: 1027708697201-lsvif0bbt6tkpjanogrcecveuiflf1um.apps.googleusercontent.com
      clientSecret:
        name: google-client-secret
      hostedDomain: redhat.com
    mappingMethod: claim
    name: google
    type: Google
