kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"processor:latest","namespace":"groundbreaker-edgefac1"},"fieldPath":"spec.template.spec.containers[?(@.name==\"processor\")].image","pause":"false"}]
  name: processor
  namespace: groundbreaker-edgefac1
  labels:
    app: processor
    app.kubernetes.io/component: processor
    app.kubernetes.io/instance: processor
    app.kubernetes.io/name: processor
    app.kubernetes.io/part-of: groundbreaker-edgfac1
    app.openshift.io/runtime: python
    app.openshift.io/runtime-namespace: groundbreaker-edgefac1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: processor
        deployment: processor
    spec:
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: images
      containers:
        - name: processor
          image: >-
            image-registry.openshift-image-registry.svc:5000/groundbreaker-edgefac1/processor@sha256:139b1862470280bdd219b91e5d5522cd0f8d26a5c39375afe2e6109522474528
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: images
              mountPath: /images
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
