kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"forwarder:latest","namespace":"groundbreaker-edgefac1"},"fieldPath":"spec.template.spec.containers[?(@.name==\"forwarder\")].image","pause":"false"}]
  name: forwarder
  namespace: groundbreaker-edgefac1
  labels:
    app: forwarder
    app.kubernetes.io/component: forwarder
    app.kubernetes.io/instance: forwarder
    app.kubernetes.io/name: forwarder
    app.kubernetes.io/part-of: groundbreaker-edgfac1
    app.openshift.io/runtime: python
    app.openshift.io/runtime-namespace: groundbreaker-edgefac1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forwarder
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: forwarder
        deployment: forwarder
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: images
      containers:
        - name: forwarder
          image: >-
            image-registry.openshift-image-registry.svc:5000/groundbreaker-edgefac1/forwarder@sha256:8df99478f68096b2c2acc95913f177c55413969145663849fdebbee7e59f0b94
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: images
              mountPath: /images
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
