apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: groundbreaker-s3
  namespace: openshift-cloud-credential-operator
spec:
  serviceAccountNames:
  - default
  secretRef:
    name: s3-creds
    namespace: groundbreaker-prod
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      action:
      - s3:CreateBucket
      - s3:PutBucketTagging
      - s3:PutObject
      - s3:PutObjectAcl
      resource: "*"
