apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: groundbreaker-azure-storage
  namespace: openshift-cloud-credential-operator
spec:
  serviceAccountNames:
  - default
  secretRef:
    name: azure-creds
    namespace: groundbreaker-prod
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AzureProviderSpec
    roleBindings:
      - role: Contributor
