apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-ingress
  namespace: openshift-ingress
spec:
  secretName: letsencrypt-ingress
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  commonName: PLACEHOLDER
  usages:
    - server auth
    - client auth
  dnsNames: []
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
