apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: groundbreaker-cloud-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: groundbreaker
              operator: In
              values:
                - cloud
